tumor-growth-coefficient	1.1132
TRAMETINIB	Tumor-Inhibition-Coefficient	-0.10463405746684767
tumor-growth-coefficient	1.1132
DABRAFENIB	Tumor-Inhibition-Coefficient	-0.01
tumor-growth-coefficient	1.1132
NIVOLUMAB	Tumor-Inhibition-Coefficient	-0.04750717363296045
tumor-growth-coefficient	1.1132
PEMBROLIZUMAB	Tumor-Inhibition-Coefficient	-0.10811476482832139
tumor-growth-coefficient	1.1132
VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.01
PEMBROLIZUMAB|VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.18335116054785403
NIVOLUMAB|PEMBROLIZUMAB	Tumor-Inhibition-Coefficient	-0.0968249700078286
DABRAFENIB|NIVOLUMAB	Tumor-Inhibition-Coefficient	-0.15856740851442153
DABRAFENIB|VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.15600698069472502
NIVOLUMAB|VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.15856740851442153
TRAMETINIB|NIVOLUMAB	Tumor-Inhibition-Coefficient	-0.07078640748034142
TRAMETINIB|VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.21557657097646604
DABRAFENIB|PEMBROLIZUMAB	Tumor-Inhibition-Coefficient	-0.18335116054785403
TRAMETINIB|DABRAFENIB	Tumor-Inhibition-Coefficient	-0.21557657097646604
TRAMETINIB|PEMBROLIZUMAB	Tumor-Inhibition-Coefficient	-0.10069899731312258
