tumor-growth-coefficient	1.1132
TRAMETINIB	Tumor-Inhibition-Coefficient	-0.007531625314051035
tumor-growth-coefficient	1.1132
DABRAFENIB	Tumor-Inhibition-Coefficient	-0.01
tumor-growth-coefficient	1.1132
NIVOLUMAB	Tumor-Inhibition-Coefficient	-0.047507173632960475
tumor-growth-coefficient	1.1132
PEMBROLIZUMAB	Tumor-Inhibition-Coefficient	-0.10811476482832136
tumor-growth-coefficient	1.1132
VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.01
PEMBROLIZUMAB|VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.18335116054785403
DABRAFENIB|PEMBROLIZUMAB	Tumor-Inhibition-Coefficient	-0.18335116054785403
NIVOLUMAB|PEMBROLIZUMAB	Tumor-Inhibition-Coefficient	-0.09682497000782862
DABRAFENIB|VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.15600698069472502
NIVOLUMAB|VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.15856740851442155
DABRAFENIB|NIVOLUMAB	Tumor-Inhibition-Coefficient	-0.15856740851442155
TRAMETINIB|DABRAFENIB	Tumor-Inhibition-Coefficient	-0.17478131681873849
TRAMETINIB|PEMBROLIZUMAB	Tumor-Inhibition-Coefficient	-0.05923752564040731
TRAMETINIB|NIVOLUMAB	Tumor-Inhibition-Coefficient	-0.04427816388399888
TRAMETINIB|VEMURAFENIB	Tumor-Inhibition-Coefficient	-0.17478131681873849
